### ISSUE TITLE
abroad version v3.2.0

### ISSUE THREAD

**Issue by Mikescops** [Brooooooklyn/Clipboard#17]
Hello,

Can you trigger a release for the version v3.2.0 of the abroad? 

https://github.com/1Password/arboard/releases/tag/v3.2.0

**Comment by Brooooooklyn** [comment]
Released in https://github.com/Brooooooklyn/Clipboard/releases/tag/v1.0.2

**Comment by Mikescops** [comment]
Thanks a lot!
